import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import Nav from "./components/nav"
import { ClerkProvider } from "@clerk/nextjs"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    //é chamado o ClerkProvider para efeturar o login
    <ClerkProvider>
      <html lang="en">
        <body className={`min-h-screen ${inter.className}`}>
          <Nav />
          <div className="flex justify-center items-center p-24">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
